## Local Development Containers for the core service

services: 
  core-service:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    networks:
      - d-core_default
    environment:
      - name=value

networks:
  d-core_default:
    external: true