global:
  scrape_interval: 10s
  evaluation_interval: 10s

scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets: ["metrics:9090"]

  - job_name: core-service
    metrics_path: /metrics
    static_configs:
      - targets: ["core-service:3000"]

  - job_name: core-service-local
    metrics_path: /metrics
    static_configs:
      - targets: ["host.docker.internal:3000"]
