global:
  scrape_interval: 5s
  evaluation_interval: 5s

scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets: ["metrics:9090"]

  - job_name: core-service
    metrics_path: /metrics
    static_configs:
      - targets: ["core-service:3000"]
